version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api/:/var/www/api
      - ./api/_docker/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./api/_docker/app/Dockerfile
    volumes:
      - ./api/:/var/www/api
    container_name: app
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    volumes:
      - ./api/tmp/db:/var/lib/pgsql
    environment:
      POSTGRES_DB: operations_manager_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8101:5432"
    container_name: db

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    working_dir: /var/www/web
    volumes:
      - ./web:/var/www/web
    ports:
      - "3000:3000"
    command: npm run dev
    tty: true
    depends_on:
      - app